spring.application.name=BE_DANTN

logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}


spring.jpa.properties.hibernate.use_nationalized_character_data=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=DATA_BV_DOT1;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# create: Xóa và tạo lại DB mỗi lần chạy. Tốt cho dev để đảm bảo sự nhất quán.
# update: Cố gắng cập nhật schema. Dễ gây lỗi nếu dữ liệu cũ không tương thích.
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
logging.level.net.ttddyy.dsproxy.listener=debug
logging.level.org.hibernate.type=trace

spring.docker.compose.enabled=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Spring Mail Configuration (SMTP Gmail Template)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhphong26012006@gmail.com
spring.mail.password=ckdq osoq rozp vimm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# VNPAY Sandbox Configuration
vnpay.tmn-code=8E54YJYF
vnpay.hash-secret=O2BZHAXIM7I78OZJX9ZPCHQ13D57SAGO
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/vnpay-return
