INSERT INTO hoa_don(
    id_nhan_vien,
    id_khach_hang,
    id_phieu_giam_gia,
    ma_hoa_don,
    loai_hoa_don,
    phi_van_chuyen,
    so_tien_goc,
    so_tien_giam,
    tong_tien_thanh_toan,
    ten_khach_hang,
    dia_chi_khach_hang,
    so_dien_thoai,
    trang_thai,
    ghi_chu,
    ngay_nhan_hang,
    ngay_sua,
    ngay_tao,
    ngay_thanh_toan
)
VALUES
    (
        1,
        1,
        NULL,
        'HD001',
        'ONLINE',
        30000,
        500000,
        50000,
        480000,
        'Nguyen Van An',
        'Bao Loc, Lam Dong',
        '0987654321',
        'CHO_XAC_NHAN',
        'Don hang online',
        NULL,
        NULL,
        CURRENT_TIMESTAMP,
        NULL
    );

INSERT INTO hoa_don(
    id_nhan_vien,
    id_khach_hang,
    id_phieu_giam_gia,
    ma_hoa_don,
    loai_hoa_don,
    phi_van_chuyen,
    so_tien_goc,
    so_tien_giam,
    tong_tien_thanh_toan,
    ten_khach_hang,
    dia_chi_khach_hang,
    so_dien_thoai,
    trang_thai,
    ghi_chu,
    ngay_nhan_hang,
    ngay_sua,
    ngay_tao,
    ngay_thanh_toan
)
VALUES
    (
        2,
        2,
        NULL,
        'HD002',
        'TAI_QUAY',
        0,
        700000,
        0,
        700000,
        'Le Thi Mai',
        'Da Lat, Lam Dong',
        '0911222333',
        'HOAN_THANH',
        'Don hang tai quay',
        CURRENT_TIMESTAMP,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );